In [104]:
import sys
import torch

In [105]:
print(sys.version)
print(torch.__version__)

3.13.11 (main, Jan 13 2026, 17:36:15) [Clang 21.1.4 ]
2.11.0+rocm7.2


In [106]:
points = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
points.dtype

torch.float32

In [107]:
points.long().dtype

torch.int64

In [108]:
points = torch.randn(10, 2)
points

tensor([[ 0.1677, -0.8241],
        [ 0.5650,  1.2181],
        [-1.2981, -0.9947],
        [ 1.0780, -0.2416],
        [ 0.0284, -0.0249],
        [-0.7129, -0.0346],
        [ 0.3740, -0.9101],
        [-1.3288, -1.4277],
        [-0.0639, -0.2169],
        [-0.7961,  0.8448]])

In [109]:
points_double = points.type(torch.double)
points_double

tensor([[ 0.1677, -0.8241],
        [ 0.5650,  1.2181],
        [-1.2981, -0.9947],
        [ 1.0780, -0.2416],
        [ 0.0284, -0.0249],
        [-0.7129, -0.0346],
        [ 0.3740, -0.9101],
        [-1.3288, -1.4277],
        [-0.0639, -0.2169],
        [-0.7961,  0.8448]], dtype=torch.float64)

In [110]:
points_np = points.numpy()
points_np

array([[ 0.16774766, -0.8240545 ],
       [ 0.5649701 ,  1.2180505 ],
       [-1.298115  , -0.994696  ],
       [ 1.0779933 , -0.2416239 ],
       [ 0.02844005, -0.02493242],
       [-0.71293074, -0.03462739],
       [ 0.3740422 , -0.9100647 ],
       [-1.3287761 , -1.4276687 ],
       [-0.0638969 , -0.21693003],
       [-0.79607284,  0.8447847 ]], dtype=float32)

In [111]:
points_torch = torch.from_numpy(points_np)
points_torch, points_torch.dtype

(tensor([[ 0.1677, -0.8241],
         [ 0.5650,  1.2181],
         [-1.2981, -0.9947],
         [ 1.0780, -0.2416],
         [ 0.0284, -0.0249],
         [-0.7129, -0.0346],
         [ 0.3740, -0.9101],
         [-1.3288, -1.4277],
         [-0.0639, -0.2169],
         [-0.7961,  0.8448]]),
 torch.float32)

In [112]:
# with open('./data/points.t', 'wb') as file:
#     torch.save(points, file)
torch.save(points, "./data/points.t")

In [113]:
points = torch.load("./data/points.t")

In [114]:
import h5py

file = h5py.File("./data/coords.hdf5", "w")
dataset = file.create_dataset("coords", data=points.numpy())
file.close()

OSError: Unable to synchronously create file (unable to truncate a file which is already open)

In [ ]:
file = h5py.File("./data/coords.hdf5", "r")
dataset = file["coords"]
last_points = dataset[1:]

In [ ]:
last_points

array([[-0.14084932,  0.884003  ],
       [ 0.07667075, -0.717213  ],
       [ 1.3924478 ,  2.052169  ],
       [ 0.09289169, -1.6396949 ],
       [ 2.014282  ,  1.3716258 ],
       [ 1.1605763 , -2.2501109 ],
       [ 0.5920812 , -0.382032  ],
       [-0.62008774,  0.11655387],
       [ 0.00514703, -0.11762989]], dtype=float32)

In [ ]:
last_points_torch = torch.from_numpy(last_points)

In [ ]:
last_points_torch

tensor([[-0.1408,  0.8840],
        [ 0.0767, -0.7172],
        [ 1.3924,  2.0522],
        [ 0.0929, -1.6397],
        [ 2.0143,  1.3716],
        [ 1.1606, -2.2501],
        [ 0.5921, -0.3820],
        [-0.6201,  0.1166],
        [ 0.0051, -0.1176]])

In [ ]:
torch.cuda.is_available()

last_points_torch.to(device="cuda:0")

tensor([[-0.1408,  0.8840],
        [ 0.0767, -0.7172],
        [ 1.3924,  2.0522],
        [ 0.0929, -1.6397],
        [ 2.0143,  1.3716],
        [ 1.1606, -2.2501],
        [ 0.5921, -0.3820],
        [-0.6201,  0.1166],
        [ 0.0051, -0.1176]], device='cuda:0')

In [ ]:
torch.cuda.get_device_properties()

_CudaDeviceProperties(name='AMD Radeon RX 9060 XT', major=12, minor=0, gcnArchName='gfx1200', total_memory=16304MB, multi_processor_count=16, uuid=66353839-3137-3937-3538-333038386363, pci_bus_id=3, pci_device_id=0, pci_domain_id=0, L2_cache_size=4MB)

In [ ]:
points_gpu = points.to(device="cuda", dtype=torch.float32)

In [ ]:
points_gpu * 2

tensor([[-0.0573,  1.4477],
        [-0.2817,  1.7680],
        [ 0.1533, -1.4344],
        [ 2.7849,  4.1043],
        [ 0.1858, -3.2794],
        [ 4.0286,  2.7433],
        [ 2.3212, -4.5002],
        [ 1.1842, -0.7641],
        [-1.2402,  0.2331],
        [ 0.0103, -0.2353]], device='cuda:0')

In [ ]:
a = torch.ones(6, 3, 3)
a

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
a.zero_()

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
a

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

### Exercises

Create a tensor a from list(range(9)). Predict then check what the size, off- set, and strides are.

In [ ]:
a = torch.tensor(list(range(9)))
a  # Size(9), off-set: 0, stride: 1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a.size(), a.storage_offset(), a.stride()

(torch.Size([9]), 0, (1,))

Create a tensor b = a.view(3, 3). What is the value of b[1,1]?

In [ ]:
b = a.view(3, 3)  # Size([9]) -> Size([3,3])
b.size(), b

(torch.Size([3, 3]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]))

In [ ]:
b[1, 1]  # 4
b.stride()

(3, 1)

Create a tensor c = b[1:,1:]. Predict then check what the size, offset, and strides are

In [ ]:
c = b[1:, 1:]
# b[1:,] -> [[3, 4, 5], [6, 7, 8]], b[1:, 1:] -> [[4, 5], [7, 8]]
# size = Size([2, 2]), offset = 4, stride = (2, 1) -> blad, poniewaz storage sie nie zmienia co innego w przypadku "contiguous"
c.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [ ]:
c.size(), c.storage_offset(), c.stride()

(torch.Size([2, 2]), 4, (3, 1))

In [ ]:
c

tensor([[4, 5],
        [7, 8]])

Pick a mathematical operation like cosine or square root. Can you find a corre- sponding function in the torch library?

In [ ]:
torch.cos(c)

tensor([[-0.6536,  0.2837],
        [ 0.7539, -0.1455]])

In [ ]:
# torch.sqrt(c)
c.float().sqrt_()

tensor([[0., 0.],
        [0., 0.]])

Is there a version of your function that operates in-place?

In [ ]:
c.zero_()

tensor([[0, 0],
        [0, 0]])