In [31]:
import sys
import torch

In [32]:
print(f"python version: {sys.version}")
print(
    f"version: {torch.__version__}, device: {torch.cuda.get_device_name() if torch.cuda.is_available() else 'No GPU'}"
)

python version: 3.13.11 (main, Jan 13 2026, 17:36:15) [Clang 21.1.4 ]
version: 2.11.0+rocm7.2, device: AMD Radeon RX 9060 XT


In [33]:
matrix = torch.zeros(3, 3)
matrix

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [34]:
tensor = torch.ones(3, 3, 3)
tensor

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [35]:
tensor[0][2, 2] = 2
tensor[0]

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 2.]])

In [36]:
tensor.storage()

 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 27]

In [37]:
second_batch = tensor[1]

In [38]:
second_batch.storage_offset(), second_batch.size(), second_batch.stride()

(9, torch.Size([3, 3]), (3, 1))

In [39]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.size()

torch.Size([2])

In [40]:
second_point.storage_offset()

2

In [41]:
second_point.stride()

(1,)

In [42]:
subtensor = points[1].clone()

In [43]:
subtensor

tensor([2., 1.])

In [44]:
subtensor[0] = 10

In [45]:
points, subtensor

(tensor([[1., 4.],
         [2., 1.],
         [3., 5.]]),
 tensor([10.,  1.]))

In [46]:
points_t = points.t()

In [51]:
id(points.storage()) == id(points_t.storage())

False

In [49]:
points.stride()

(2, 1)

In [50]:
points_t.stride()

(1, 2)

In [52]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [53]:
X.storage()

 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [60]:
X.stride(), X.size(), X

((3, 1),
 torch.Size([2, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [58]:
X_t = X.t()

In [61]:
X_t.stride(), X_t.size(), X_t

((1, 3),
 torch.Size([3, 2]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]))

In [69]:
some_tensor = torch.ones(3, 4, 5)
some_tensor_t = some_tensor.transpose(0, 2)
some_tensor.shape

torch.Size([3, 4, 5])

In [70]:
some_tensor_t.shape

torch.Size([5, 4, 3])

In [71]:
some_tensor.stride(), some_tensor_t.stride()

((20, 5, 1), (1, 5, 20))

In [72]:
points.is_contiguous()

True

In [73]:
points_t.is_contiguous()

False

contiguous tensors

In [74]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [75]:
points_t.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [76]:
points_t.stride()

(1, 2)

In [78]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [80]:
points_t_cont.stride()

(3, 1)

In [81]:
points_t_cont.storage()

 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]