In [1]:
import sys
import torch

In [3]:
print(sys.version)
print(torch.__version__)

3.13.11 (main, Jan 13 2026, 17:36:15) [Clang 21.1.4 ]
2.11.0+rocm7.2


In [4]:
points = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
points.dtype

torch.float32

In [ ]:
points.long().dtype

torch.int64

In [ ]:
points = torch.randn(10, 2)
points

tensor([[-0.0260,  0.6037],
        [-0.3699,  0.4513],
        [ 0.4413,  1.9528],
        [ 0.4446, -0.6134],
        [ 0.7330, -1.6282],
        [ 0.5441, -0.6019],
        [-0.6509,  1.5925],
        [ 1.9315,  1.9634],
        [ 0.4133, -0.4499],
        [-1.1552,  1.5152]])

In [7]:
points_double = points.type(torch.double)
points_double

tensor([[-0.0260,  0.6037],
        [-0.3699,  0.4513],
        [ 0.4413,  1.9528],
        [ 0.4446, -0.6134],
        [ 0.7330, -1.6282],
        [ 0.5441, -0.6019],
        [-0.6509,  1.5925],
        [ 1.9315,  1.9634],
        [ 0.4133, -0.4499],
        [-1.1552,  1.5152]], dtype=torch.float64)

In [8]:
points_np = points.numpy()
points_np

array([[-0.02604929,  0.6037431 ],
       [-0.36985114,  0.45126742],
       [ 0.44129074,  1.9528018 ],
       [ 0.44455713, -0.6134414 ],
       [ 0.73295635, -1.6281501 ],
       [ 0.5440503 , -0.6018561 ],
       [-0.6509317 ,  1.5924662 ],
       [ 1.9314884 ,  1.9634204 ],
       [ 0.41332296, -0.44986513],
       [-1.1551913 ,  1.5151573 ]], dtype=float32)

In [11]:
points_torch = torch.from_numpy(points_np)
points_torch, points_torch.dtype

(tensor([[-0.0260,  0.6037],
         [-0.3699,  0.4513],
         [ 0.4413,  1.9528],
         [ 0.4446, -0.6134],
         [ 0.7330, -1.6282],
         [ 0.5441, -0.6019],
         [-0.6509,  1.5925],
         [ 1.9315,  1.9634],
         [ 0.4133, -0.4499],
         [-1.1552,  1.5152]]),
 torch.float32)

In [ ]:
# with open('./data/points.t', 'wb') as file:
#     torch.save(points, file)
torch.save(points, "./data/points.t")

In [ ]:
points = torch.load("./data/points.t")